version: '3.9'

services:
  trojes-api:
    image: esjuliorafael/nexus-api:latest
    container_name: trojes-api
    restart: always
    env_file: .env
    environment:
      - PORT=8080
    networks:
      - nexus-network

  trojes-front:
    image: esjuliorafael/nexus-storefront:latest
    container_name: trojes-front
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
      - INTERNAL_API_URL=http://trojes-api:8080/api/v1
    depends_on:
      - trojes-api
    networks:
      - nexus-network

  trojes-admin:
    image: esjuliorafael/nexus-admin:latest
    container_name: trojes-admin
    restart: always
    networks:
      - nexus-network

networks:
  nexus-network:
    external: true
    name: nexus-global-network
